const BLPAPI_CORRELATION_TYPE_UNSET   = 0
const BLPAPI_CORRELATION_TYPE_INT     = 1
const BLPAPI_CORRELATION_TYPE_POINTER = 2
const BLPAPI_CORRELATION_TYPE_AUTOGEN = 3
const BLPAPI_CORRELATION_MAX_CLASS_ID = ((1 << 16)-1)

const BLPAPI_DATETIME_YEAR_PART         = 0x1
const BLPAPI_DATETIME_MONTH_PART        = 0x2
const BLPAPI_DATETIME_DAY_PART          = 0x4
const BLPAPI_DATETIME_OFFSET_PART       = 0x8
const BLPAPI_DATETIME_HOURS_PART        = 0x10
const BLPAPI_DATETIME_MINUTES_PART      = 0x20
const BLPAPI_DATETIME_SECONDS_PART      = 0x40
const BLPAPI_DATETIME_MILLISECONDS_PART = 0x80
const BLPAPI_DATETIME_FRACSECONDS_PART  = 0x80
const BLPAPI_DATETIME_DATE_PART         = BLPAPI_DATETIME_YEAR_PART|BLPAPI_DATETIME_MONTH_PART|BLPAPI_DATETIME_DAY_PART
const BLPAPI_DATETIME_TIME_PART         = BLPAPI_DATETIME_HOURS_PART|BLPAPI_DATETIME_MINUTES_PART|BLPAPI_DATETIME_SECONDS_PART
const BLPAPI_DATETIME_TIMEMILLI_PART    = BLPAPI_DATETIME_TIME_PART|BLPAPI_DATETIME_MILLISECONDS_PART
const BLPAPI_DATETIME_TIMEFRACSECONDS_PART = BLPAPI_DATETIME_TIME_PART|BLPAPI_DATETIME_FRACSECONDS_PART

const BLPAPI_EVENTTYPE_ADMIN                = 1
const BLPAPI_EVENTTYPE_SESSION_STATUS       = 2
const BLPAPI_EVENTTYPE_SUBSCRIPTION_STATUS  = 3
const BLPAPI_EVENTTYPE_REQUEST_STATUS       = 4
const BLPAPI_EVENTTYPE_RESPONSE             = 5
const BLPAPI_EVENTTYPE_PARTIAL_RESPONSE     = 6
const BLPAPI_EVENTTYPE_SUBSCRIPTION_DATA    = 8
const BLPAPI_EVENTTYPE_SERVICE_STATUS       = 9
const BLPAPI_EVENTTYPE_TIMEOUT              = 10
const BLPAPI_EVENTTYPE_AUTHORIZATION_STATUS = 11
const BLPAPI_EVENTTYPE_RESOLUTION_STATUS    = 12
const BLPAPI_EVENTTYPE_TOPIC_STATUS         = 13
const BLPAPI_EVENTTYPE_TOKEN_STATUS         = 14
const BLPAPI_EVENTTYPE_REQUEST              = 15

const BLPAPI_ELEMENT_INDEX_END = 0xffffffff

const BLPAPI_SUBSCRIPTIONSTATUS_UNSUBSCRIBED         = 0
const BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBING          = 1
const BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBED           = 2
const BLPAPI_SUBSCRIPTIONSTATUS_CANCELLED            = 3
const BLPAPI_SUBSCRIPTIONSTATUS_PENDING_CANCELLATION = 4
      
const BLPAPI_CLIENTMODE_AUTO         = 0
const BLPAPI_CLIENTMODE_DAPI         = 1
const BLPAPI_CLIENTMODE_SAPI         = 2
const BLPAPI_CLIENTMODE_COMPAT_33X   = 16

CORRELATION_TYPE_INT                    = BLPAPI_CORRELATION_TYPE_INT                   
CORRELATION_TYPE_POINTER                = BLPAPI_CORRELATION_TYPE_POINTER               
DATETIME_YEAR_PART                      = BLPAPI_DATETIME_YEAR_PART                     
DATETIME_MONTH_PART                     = BLPAPI_DATETIME_MONTH_PART                    
DATETIME_DAY_PART                       = BLPAPI_DATETIME_DAY_PART                      
DATETIME_OFFSET_PART                    = BLPAPI_DATETIME_OFFSET_PART                   
DATETIME_HOURS_PART                     = BLPAPI_DATETIME_HOURS_PART                    
DATETIME_MINUTES_PART                   = BLPAPI_DATETIME_MINUTES_PART                  
DATETIME_SECONDS_PART                   = BLPAPI_DATETIME_SECONDS_PART                  
DATETIME_MILLISECONDS_PART              = BLPAPI_DATETIME_MILLISECONDS_PART             
DATETIME_FRACSECONDS_PART               = BLPAPI_DATETIME_FRACSECONDS_PART              
DATETIME_DATE_PART                      = BLPAPI_DATETIME_DATE_PART                     
DATETIME_TIME_PART                      = BLPAPI_DATETIME_TIME_PART                     
DATETIME_TIMEMILLI_PART                 = BLPAPI_DATETIME_TIMEMILLI_PART                
DATETIME_TIMEFRACSECONDS_PART           = BLPAPI_DATETIME_TIMEFRACSECONDS_PART          
EVENTTYPE_ADMIN                         = BLPAPI_EVENTTYPE_ADMIN                        
EVENTTYPE_SESSION_STATUS                = BLPAPI_EVENTTYPE_SESSION_STATUS               
EVENTTYPE_SUBSCRIPTION_STATUS           = BLPAPI_EVENTTYPE_SUBSCRIPTION_STATUS          
EVENTTYPE_REQUEST_STATUS                = BLPAPI_EVENTTYPE_REQUEST_STATUS               
EVENTTYPE_RESPONSE                      = BLPAPI_EVENTTYPE_RESPONSE                     
EVENTTYPE_PARTIAL_RESPONSE              = BLPAPI_EVENTTYPE_PARTIAL_RESPONSE             
EVENTTYPE_SUBSCRIPTION_DATA             = BLPAPI_EVENTTYPE_SUBSCRIPTION_DATA            
EVENTTYPE_SERVICE_STATUS                = BLPAPI_EVENTTYPE_SERVICE_STATUS               
EVENTTYPE_TIMEOUT                       = BLPAPI_EVENTTYPE_TIMEOUT                      
EVENTTYPE_AUTHORIZATION_STATUS          = BLPAPI_EVENTTYPE_AUTHORIZATION_STATUS         
EVENTTYPE_RESOLUTION_STATUS             = BLPAPI_EVENTTYPE_RESOLUTION_STATUS            
EVENTTYPE_TOPIC_STATUS                  = BLPAPI_EVENTTYPE_TOPIC_STATUS                 
EVENTTYPE_TOKEN_STATUS                  = BLPAPI_EVENTTYPE_TOKEN_STATUS                 
EVENTTYPE_REQUEST                       = BLPAPI_EVENTTYPE_REQUEST                      
ELEMENT_INDEX_END                       = BLPAPI_ELEMENT_INDEX_END                      
SUBSCRIPTIONSTATUS_UNSUBSCRIBED         = BLPAPI_SUBSCRIPTIONSTATUS_UNSUBSCRIBED        
SUBSCRIPTIONSTATUS_SUBSCRIBING          = BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBING         
SUBSCRIPTIONSTATUS_SUBSCRIBED           = BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBED          
SUBSCRIPTIONSTATUS_CANCELLED            = BLPAPI_SUBSCRIPTIONSTATUS_CANCELLED           
SUBSCRIPTIONSTATUS_PENDING_CANCELLATION = BLPAPI_SUBSCRIPTIONSTATUS_PENDING_CANCELLATION
CLIENTMODE_AUTO                         = BLPAPI_CLIENTMODE_AUTO                        
CLIENTMODE_DAPI                         = BLPAPI_CLIENTMODE_DAPI                        
CLIENTMODE_SAPI                         = BLPAPI_CLIENTMODE_SAPI                        
CLIENTMODE_COMPAT_33X                   = BLPAPI_CLIENTMODE_COMPAT_33X     

export BLPAPI_CORRELATION_TYPE_INT                    ,
       BLPAPI_CORRELATION_TYPE_POINTER                ,
       BLPAPI_DATETIME_YEAR_PART                      ,
       BLPAPI_DATETIME_MONTH_PART                     ,
       BLPAPI_DATETIME_DAY_PART                       ,
       BLPAPI_DATETIME_OFFSET_PART                    ,
       BLPAPI_DATETIME_HOURS_PART                     ,
       BLPAPI_DATETIME_MINUTES_PART                   ,
       BLPAPI_DATETIME_SECONDS_PART                   ,
       BLPAPI_DATETIME_MILLISECONDS_PART              ,
       BLPAPI_DATETIME_FRACSECONDS_PART               ,
       BLPAPI_DATETIME_DATE_PART                      ,
       BLPAPI_DATETIME_TIME_PART                      ,
       BLPAPI_DATETIME_TIMEMILLI_PART                 ,
       BLPAPI_DATETIME_TIMEFRACSECONDS_PART           ,
       BLPAPI_EVENTTYPE_ADMIN                         ,
       BLPAPI_EVENTTYPE_SESSION_STATUS                ,
       BLPAPI_EVENTTYPE_SUBSCRIPTION_STATUS           ,
       BLPAPI_EVENTTYPE_REQUEST_STATUS                ,
       BLPAPI_EVENTTYPE_RESPONSE                      ,
       BLPAPI_EVENTTYPE_PARTIAL_RESPONSE              ,
       BLPAPI_EVENTTYPE_SUBSCRIPTION_DATA             ,
       BLPAPI_EVENTTYPE_SERVICE_STATUS                ,
       BLPAPI_EVENTTYPE_TIMEOUT                       ,
       BLPAPI_EVENTTYPE_AUTHORIZATION_STATUS          ,
       BLPAPI_EVENTTYPE_RESOLUTION_STATUS             ,
       BLPAPI_EVENTTYPE_TOPIC_STATUS                  ,
       BLPAPI_EVENTTYPE_TOKEN_STATUS                  ,
       BLPAPI_EVENTTYPE_REQUEST                       ,
       BLPAPI_ELEMENT_INDEX_END                       ,
       BLPAPI_SUBSCRIPTIONSTATUS_UNSUBSCRIBED         ,
       BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBING          ,
       BLPAPI_SUBSCRIPTIONSTATUS_SUBSCRIBED           ,
       BLPAPI_SUBSCRIPTIONSTATUS_CANCELLED            ,
       BLPAPI_SUBSCRIPTIONSTATUS_PENDING_CANCELLATION ,
       BLPAPI_CLIENTMODE_AUTO                         ,
       BLPAPI_CLIENTMODE_DAPI                         ,
       BLPAPI_CLIENTMODE_SAPI                         ,
       BLPAPI_CLIENTMODE_COMPAT_33X                   