# begin enum blpapi_DataType_t
const BLPAPI_DATATYPE_BOOL = 1 
const BLPAPI_DATATYPE_CHAR = 2 
const BLPAPI_DATATYPE_BYTE = 3 
const BLPAPI_DATATYPE_INT32 = 4 
const BLPAPI_DATATYPE_INT64 = 5 
const BLPAPI_DATATYPE_FLOAT32 = 6 
const BLPAPI_DATATYPE_FLOAT64 = 7 
const BLPAPI_DATATYPE_STRING = 8 
const BLPAPI_DATATYPE_BYTEARRAY = 9 
const BLPAPI_DATATYPE_DATE = 10 
const BLPAPI_DATATYPE_TIME = 11 
const BLPAPI_DATATYPE_DECIMAL = 12 
const BLPAPI_DATATYPE_DATETIME = 13 
const BLPAPI_DATATYPE_ENUMERATION = 14 
const BLPAPI_DATATYPE_SEQUENCE = 15 
const BLPAPI_DATATYPE_CHOICE = 16 
const BLPAPI_DATATYPE_CORRELATION_ID = 17 
# end enum blpapi_DataType_t

DATATYPE_BOOL           = BLPAPI_DATATYPE_BOOL          
DATATYPE_CHAR           = BLPAPI_DATATYPE_CHAR          
DATATYPE_BYTE           = BLPAPI_DATATYPE_BYTE          
DATATYPE_INT32          = BLPAPI_DATATYPE_INT32         
DATATYPE_INT64          = BLPAPI_DATATYPE_INT64         
DATATYPE_FLOAT32        = BLPAPI_DATATYPE_FLOAT32       
DATATYPE_FLOAT64        = BLPAPI_DATATYPE_FLOAT64       
DATATYPE_STRING         = BLPAPI_DATATYPE_STRING        
DATATYPE_BYTEARRAY      = BLPAPI_DATATYPE_BYTEARRAY     
DATATYPE_DATE           = BLPAPI_DATATYPE_DATE          
DATATYPE_TIME           = BLPAPI_DATATYPE_TIME          
DATATYPE_DECIMAL        = BLPAPI_DATATYPE_DECIMAL       
DATATYPE_DATETIME       = BLPAPI_DATATYPE_DATETIME      
DATATYPE_ENUMERATION    = BLPAPI_DATATYPE_ENUMERATION   
DATATYPE_SEQUENCE       = BLPAPI_DATATYPE_SEQUENCE      
DATATYPE_CHOICE         = BLPAPI_DATATYPE_CHOICE        
DATATYPE_CORRELATION_ID = BLPAPI_DATATYPE_CORRELATION_ID

export BLPAPI_DATATYPE_BOOL           ,
       BLPAPI_DATATYPE_CHAR           ,
       BLPAPI_DATATYPE_BYTE           ,
       BLPAPI_DATATYPE_INT32          ,
       BLPAPI_DATATYPE_INT64          ,
       BLPAPI_DATATYPE_FLOAT32        ,
       BLPAPI_DATATYPE_FLOAT64        ,
       BLPAPI_DATATYPE_STRING         ,
       BLPAPI_DATATYPE_BYTEARRAY      ,
       BLPAPI_DATATYPE_DATE           ,
       BLPAPI_DATATYPE_TIME           ,
       BLPAPI_DATATYPE_DECIMAL        ,
       BLPAPI_DATATYPE_DATETIME       ,
       BLPAPI_DATATYPE_ENUMERATION    ,
       BLPAPI_DATATYPE_SEQUENCE       ,
       BLPAPI_DATATYPE_CHOICE         ,
       BLPAPI_DATATYPE_CORRELATION_ID 